language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "bathtub-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: rocky-caverns-23281 # see README
  api_key:
    secure: "Mu1o76T/sbgBvOGpYwoRTCliFA7zBsdaVgydB5nuTWuMVDDLX4GbV2+gMqfIkxz3T7hk1DqZR5ughZemDLtcbcDJWxxPKmW260xYhZmilthe/93FBK/vWQf45Gk8V7FWh8oLQUwRwiFSZ8dPvJ+wLsmvKckzZQhWmS7stjAW9oB8xB++chMJkHcxaE8v8lUmJORwCMqzsqlfZkfVycCfezjpkBoH9ZrmM3Lx2MwuJKB/qDs9MY4Qb+aQbLpTiUtXrTgZmqSnOgEsyGQqtMCo/ozas0mCkFZtAuax+mpVR1DKjQAi+5IgbyorWAmqH6pBgUF9/UG4jk8DX4G3IDBv2p7zRliXqHOeiTRlSjwH+ebGx8YCV03OzT3vt3ZWYqkSzmSl5g2QgzhtStgGDGGAXjx4j6mHpoi/BIexHQy/mSkGXtn2lhikB+Nd8JlnxXi9rdEsO3ZPJ1CZP8EvNYquZKgd23WoIMJj1IZpbLS+J6b81jR4M6uprIoh2R1yQv6fQuvilwSzrmu4+O7bm7F86WnIjRl3K8rwL+uhncO2V9uqLuAjUFIWzrTPjBmtYhKXTwAWKm60EOEXGF14pDf2Vsh6rFbc3sqBSQ0OxDxmQi+Y87wgegTSc885iorKStwRrSE4EGHrCGp8GjIWXQnl7nx5BTNY1syhGanpYdytx/8=" # see README
